// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zllgzmkdwphweacsgrjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbGd6bWtkd3Bod2VhY3NncmpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTM4NzAsImV4cCI6MjA2OTAyOTg3MH0.InfRQGzoPjpXG_42riXsHPw1kv41En7q613UGR-phL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});